# Site settings - reference http://ben.balter.com/2015/02/20/jekyll-collections/
title: Kiriaze
description: The online portfolio of Constantine Kiriaze.

disqus_shortname: kiriaze

reading_time:     true
words_per_minute: 200

search:           true

# Owner/author information
owner:
  name:           Constantine Kiriaze
  avatar:         avatar.jpg
  email:          hello@kiriaze.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        kiriaze
  facebook:
  github:
  stackexchange:
  linkedin:
  instagram:
  flickr:
  tumblr:
  # google plus id, include the '+', eg +mmistakes
  google_plus:    +yourid

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
# baseurl: /path/to/blog
# baseurl: /juice # for github pages, uncomment this line, and recomment for local dev env

# Your site's domain goes here (eg: //kiriaze.github.io, http://kiriaze.com, etc)
# When testing locally leave blank or use http://localhost:4000
# url:              //kiriaze.github.io

# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /
relative_permalinks: false
permalink:   /blog/:categories/:title

# Amount of posts to show on home page
paginate: 5
# Pagination path › Important for blog page in /blog/ to work
paginate_path: blog/page:num

# Build settings
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
highlighter: true # syntax highlighting
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true
  input: GFM # github flavored markdown

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# Analytics and webmaster tools stuff goes here
google_analytics: UA-65559123-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

navigation:
 # - title: Home
 #   url: /index.html
 - title: Bio.
   url: /about
 - title: Labs.
   url: /labs
 - title: Work.
   url: /work
 - title: Words.
   url: /blog

# Default settings
defaults:
  -
    scope:
      path: ""                # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "page"
      heroText: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: ""
      comments: true
      author: ""
      layout: "post"
      heroText: true
      image:  /assets/images/projects/p2.jpg
      midnight: default
      is_post: true # automatically set is_post=true for all posts, for simple conditional checks

exclude: ['node_modules', 'gulpfile.js', 'package.json', 'assets']
# keep jekyll from removing compiled css dir
keep_files: ['assets', 'sitemap.xml']

# Src/Dest are also outlined in config.js
source: ./src
destination: ./dist
